"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file

This file is part of Celestial (https://github.com/OpenFogStack/celestial).
Copyright (c) 2021 Tobias Pfandzelter, The OpenFogStack Team.

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, version 3.

This program is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program. If not, see <http://www.gnu.org/licenses/>.
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class Empty(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___Empty = Empty

@typing_extensions.final
class HostInfo(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CPU_FIELD_NUMBER: builtins.int
    MEM_FIELD_NUMBER: builtins.int
    cpu: builtins.int
    mem: builtins.int
    def __init__(
        self,
        *,
        cpu: builtins.int = ...,
        mem: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["cpu", b"cpu", "mem", b"mem"]) -> None: ...

global___HostInfo = HostInfo

@typing_extensions.final
class ReadyInfo(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    READY_FIELD_NUMBER: builtins.int
    CREATED_FIELD_NUMBER: builtins.int
    ready: builtins.bool
    created: builtins.int
    def __init__(
        self,
        *,
        ready: builtins.bool = ...,
        created: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["created", b"created", "ready", b"ready"]) -> None: ...

global___ReadyInfo = ReadyInfo

@typing_extensions.final
class Shell(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    PLANES_FIELD_NUMBER: builtins.int
    id: builtins.int
    planes: builtins.int
    def __init__(
        self,
        *,
        id: builtins.int = ...,
        planes: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["id", b"id", "planes", b"planes"]) -> None: ...

global___Shell = Shell

@typing_extensions.final
class InitRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    DATABASE_FIELD_NUMBER: builtins.int
    DATABASEHOST_FIELD_NUMBER: builtins.int
    SHELLCOUNT_FIELD_NUMBER: builtins.int
    SHELLS_FIELD_NUMBER: builtins.int
    database: builtins.bool
    databaseHost: builtins.str
    shellcount: builtins.int
    @property
    def shells(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Shell]: ...
    def __init__(
        self,
        *,
        database: builtins.bool = ...,
        databaseHost: builtins.str = ...,
        shellcount: builtins.int = ...,
        shells: collections.abc.Iterable[global___Shell] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["database", b"database", "databaseHost", b"databaseHost", "shellcount", b"shellcount", "shells", b"shells"]) -> None: ...

global___InitRequest = InitRequest

@typing_extensions.final
class RemoteHost(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    INDEX_FIELD_NUMBER: builtins.int
    ADDR_FIELD_NUMBER: builtins.int
    index: builtins.int
    addr: builtins.str
    def __init__(
        self,
        *,
        index: builtins.int = ...,
        addr: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["addr", b"addr", "index", b"index"]) -> None: ...

global___RemoteHost = RemoteHost

@typing_extensions.final
class InitRemotesRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    INDEX_FIELD_NUMBER: builtins.int
    REMOTEHOSTS_FIELD_NUMBER: builtins.int
    index: builtins.int
    @property
    def remotehosts(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___RemoteHost]: ...
    def __init__(
        self,
        *,
        index: builtins.int = ...,
        remotehosts: collections.abc.Iterable[global___RemoteHost] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["index", b"index", "remotehosts", b"remotehosts"]) -> None: ...

global___InitRemotesRequest = InitRemotesRequest

@typing_extensions.final
class Machine(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SHELL_FIELD_NUMBER: builtins.int
    ID_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    shell: builtins.int
    """allow -1 for ground stations"""
    id: builtins.int
    name: builtins.str
    """name is only used for ground stations"""
    def __init__(
        self,
        *,
        shell: builtins.int = ...,
        id: builtins.int = ...,
        name: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["id", b"id", "name", b"name", "shell", b"shell"]) -> None: ...

global___Machine = Machine

@typing_extensions.final
class FirecrackerConfig(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VCPU_FIELD_NUMBER: builtins.int
    MEM_FIELD_NUMBER: builtins.int
    HT_FIELD_NUMBER: builtins.int
    DISK_FIELD_NUMBER: builtins.int
    KERNEL_FIELD_NUMBER: builtins.int
    ROOTFS_FIELD_NUMBER: builtins.int
    BOOTPARAMS_FIELD_NUMBER: builtins.int
    vcpu: builtins.int
    mem: builtins.int
    ht: builtins.bool
    disk: builtins.int
    kernel: builtins.str
    rootfs: builtins.str
    bootparams: builtins.str
    def __init__(
        self,
        *,
        vcpu: builtins.int = ...,
        mem: builtins.int = ...,
        ht: builtins.bool = ...,
        disk: builtins.int = ...,
        kernel: builtins.str = ...,
        rootfs: builtins.str = ...,
        bootparams: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["bootparams", b"bootparams", "disk", b"disk", "ht", b"ht", "kernel", b"kernel", "mem", b"mem", "rootfs", b"rootfs", "vcpu", b"vcpu"]) -> None: ...

global___FirecrackerConfig = FirecrackerConfig

@typing_extensions.final
class NetworkConfig(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    BANDWIDTH_FIELD_NUMBER: builtins.int
    bandwidth: builtins.int
    def __init__(
        self,
        *,
        bandwidth: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["bandwidth", b"bandwidth"]) -> None: ...

global___NetworkConfig = NetworkConfig

@typing_extensions.final
class CreateMachineRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MACHINE_FIELD_NUMBER: builtins.int
    FIRECRACKERCONFIG_FIELD_NUMBER: builtins.int
    NETWORKCONFIG_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    @property
    def machine(self) -> global___Machine: ...
    @property
    def firecrackerconfig(self) -> global___FirecrackerConfig: ...
    @property
    def networkconfig(self) -> global___NetworkConfig: ...
    status: builtins.bool
    def __init__(
        self,
        *,
        machine: global___Machine | None = ...,
        firecrackerconfig: global___FirecrackerConfig | None = ...,
        networkconfig: global___NetworkConfig | None = ...,
        status: builtins.bool = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["firecrackerconfig", b"firecrackerconfig", "machine", b"machine", "networkconfig", b"networkconfig"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["firecrackerconfig", b"firecrackerconfig", "machine", b"machine", "networkconfig", b"networkconfig", "status", b"status"]) -> None: ...

global___CreateMachineRequest = CreateMachineRequest

@typing_extensions.final
class CreateRemoteMachineRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MACHINE_FIELD_NUMBER: builtins.int
    NETWORKCONFIG_FIELD_NUMBER: builtins.int
    @property
    def machine(self) -> global___Machine: ...
    @property
    def networkconfig(self) -> global___NetworkConfig: ...
    def __init__(
        self,
        *,
        machine: global___Machine | None = ...,
        networkconfig: global___NetworkConfig | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["machine", b"machine", "networkconfig", b"networkconfig"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["machine", b"machine", "networkconfig", b"networkconfig"]) -> None: ...

global___CreateRemoteMachineRequest = CreateRemoteMachineRequest

@typing_extensions.final
class ModifyMachineRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MACHINE_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    @property
    def machine(self) -> global___Machine: ...
    status: builtins.bool
    def __init__(
        self,
        *,
        machine: global___Machine | None = ...,
        status: builtins.bool = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["machine", b"machine"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["machine", b"machine", "status", b"status"]) -> None: ...

global___ModifyMachineRequest = ModifyMachineRequest

@typing_extensions.final
class ModifyLinksRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    A_FIELD_NUMBER: builtins.int
    REMOVE_FIELD_NUMBER: builtins.int
    MODIFY_FIELD_NUMBER: builtins.int
    @property
    def a(self) -> global___Machine: ...
    @property
    def remove(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___RemoveLinkRequest]: ...
    @property
    def modify(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___ModifyLinkRequest]: ...
    def __init__(
        self,
        *,
        a: global___Machine | None = ...,
        remove: collections.abc.Iterable[global___RemoveLinkRequest] | None = ...,
        modify: collections.abc.Iterable[global___ModifyLinkRequest] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["a", b"a"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["a", b"a", "modify", b"modify", "remove", b"remove"]) -> None: ...

global___ModifyLinksRequest = ModifyLinksRequest

@typing_extensions.final
class RemoveLinkRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    B_FIELD_NUMBER: builtins.int
    @property
    def b(self) -> global___Machine: ...
    def __init__(
        self,
        *,
        b: global___Machine | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["b", b"b"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["b", b"b"]) -> None: ...

global___RemoveLinkRequest = RemoveLinkRequest

@typing_extensions.final
class ModifyLinkRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    B_FIELD_NUMBER: builtins.int
    LATENCY_FIELD_NUMBER: builtins.int
    BANDWIDTH_FIELD_NUMBER: builtins.int
    @property
    def b(self) -> global___Machine: ...
    latency: builtins.float
    bandwidth: builtins.int
    def __init__(
        self,
        *,
        b: global___Machine | None = ...,
        latency: builtins.float = ...,
        bandwidth: builtins.int = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["b", b"b"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["b", b"b", "bandwidth", b"bandwidth", "latency", b"latency"]) -> None: ...

global___ModifyLinkRequest = ModifyLinkRequest
