# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import celestial_pb2 as celestial__pb2


class CelestialStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Register = channel.unary_unary(
                '/openfogstack.celestial.celestial.Celestial/Register',
                request_serializer=celestial__pb2.RegisterRequest.SerializeToString,
                response_deserializer=celestial__pb2.RegisterResponse.FromString,
                )
        self.Init = channel.unary_unary(
                '/openfogstack.celestial.celestial.Celestial/Init',
                request_serializer=celestial__pb2.InitRequest.SerializeToString,
                response_deserializer=celestial__pb2.Empty.FromString,
                )
        self.Update = channel.stream_unary(
                '/openfogstack.celestial.celestial.Celestial/Update',
                request_serializer=celestial__pb2.StateUpdateRequest.SerializeToString,
                response_deserializer=celestial__pb2.Empty.FromString,
                )
        self.Stop = channel.unary_unary(
                '/openfogstack.celestial.celestial.Celestial/Stop',
                request_serializer=celestial__pb2.Empty.SerializeToString,
                response_deserializer=celestial__pb2.Empty.FromString,
                )


class CelestialServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Register(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Init(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Update(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Stop(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CelestialServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Register': grpc.unary_unary_rpc_method_handler(
                    servicer.Register,
                    request_deserializer=celestial__pb2.RegisterRequest.FromString,
                    response_serializer=celestial__pb2.RegisterResponse.SerializeToString,
            ),
            'Init': grpc.unary_unary_rpc_method_handler(
                    servicer.Init,
                    request_deserializer=celestial__pb2.InitRequest.FromString,
                    response_serializer=celestial__pb2.Empty.SerializeToString,
            ),
            'Update': grpc.stream_unary_rpc_method_handler(
                    servicer.Update,
                    request_deserializer=celestial__pb2.StateUpdateRequest.FromString,
                    response_serializer=celestial__pb2.Empty.SerializeToString,
            ),
            'Stop': grpc.unary_unary_rpc_method_handler(
                    servicer.Stop,
                    request_deserializer=celestial__pb2.Empty.FromString,
                    response_serializer=celestial__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'openfogstack.celestial.celestial.Celestial', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Celestial(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Register(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/openfogstack.celestial.celestial.Celestial/Register',
            celestial__pb2.RegisterRequest.SerializeToString,
            celestial__pb2.RegisterResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Init(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/openfogstack.celestial.celestial.Celestial/Init',
            celestial__pb2.InitRequest.SerializeToString,
            celestial__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Update(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/openfogstack.celestial.celestial.Celestial/Update',
            celestial__pb2.StateUpdateRequest.SerializeToString,
            celestial__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Stop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/openfogstack.celestial.celestial.Celestial/Stop',
            celestial__pb2.Empty.SerializeToString,
            celestial__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
