# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import celestial_pb2 as celestial__pb2


class CelestialStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetHostInfo = channel.unary_unary(
                '/openfogstack.celestial.celestial.Celestial/GetHostInfo',
                request_serializer=celestial__pb2.Empty.SerializeToString,
                response_deserializer=celestial__pb2.HostInfo.FromString,
                )
        self.HostReady = channel.unary_unary(
                '/openfogstack.celestial.celestial.Celestial/HostReady',
                request_serializer=celestial__pb2.Empty.SerializeToString,
                response_deserializer=celestial__pb2.ReadyInfo.FromString,
                )
        self.Init = channel.unary_unary(
                '/openfogstack.celestial.celestial.Celestial/Init',
                request_serializer=celestial__pb2.InitRequest.SerializeToString,
                response_deserializer=celestial__pb2.Empty.FromString,
                )
        self.InitRemotes = channel.unary_unary(
                '/openfogstack.celestial.celestial.Celestial/InitRemotes',
                request_serializer=celestial__pb2.InitRemotesRequest.SerializeToString,
                response_deserializer=celestial__pb2.Empty.FromString,
                )
        self.StartPeering = channel.unary_unary(
                '/openfogstack.celestial.celestial.Celestial/StartPeering',
                request_serializer=celestial__pb2.Empty.SerializeToString,
                response_deserializer=celestial__pb2.Empty.FromString,
                )
        self.CreateMachine = channel.unary_unary(
                '/openfogstack.celestial.celestial.Celestial/CreateMachine',
                request_serializer=celestial__pb2.CreateMachineRequest.SerializeToString,
                response_deserializer=celestial__pb2.Empty.FromString,
                )
        self.ModifyMachine = channel.unary_unary(
                '/openfogstack.celestial.celestial.Celestial/ModifyMachine',
                request_serializer=celestial__pb2.ModifyMachineRequest.SerializeToString,
                response_deserializer=celestial__pb2.Empty.FromString,
                )
        self.ModifyLinks = channel.unary_unary(
                '/openfogstack.celestial.celestial.Celestial/ModifyLinks',
                request_serializer=celestial__pb2.ModifyLinksRequest.SerializeToString,
                response_deserializer=celestial__pb2.Empty.FromString,
                )


class CelestialServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetHostInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HostReady(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Init(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InitRemotes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartPeering(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateMachine(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ModifyMachine(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ModifyLinks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CelestialServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetHostInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetHostInfo,
                    request_deserializer=celestial__pb2.Empty.FromString,
                    response_serializer=celestial__pb2.HostInfo.SerializeToString,
            ),
            'HostReady': grpc.unary_unary_rpc_method_handler(
                    servicer.HostReady,
                    request_deserializer=celestial__pb2.Empty.FromString,
                    response_serializer=celestial__pb2.ReadyInfo.SerializeToString,
            ),
            'Init': grpc.unary_unary_rpc_method_handler(
                    servicer.Init,
                    request_deserializer=celestial__pb2.InitRequest.FromString,
                    response_serializer=celestial__pb2.Empty.SerializeToString,
            ),
            'InitRemotes': grpc.unary_unary_rpc_method_handler(
                    servicer.InitRemotes,
                    request_deserializer=celestial__pb2.InitRemotesRequest.FromString,
                    response_serializer=celestial__pb2.Empty.SerializeToString,
            ),
            'StartPeering': grpc.unary_unary_rpc_method_handler(
                    servicer.StartPeering,
                    request_deserializer=celestial__pb2.Empty.FromString,
                    response_serializer=celestial__pb2.Empty.SerializeToString,
            ),
            'CreateMachine': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateMachine,
                    request_deserializer=celestial__pb2.CreateMachineRequest.FromString,
                    response_serializer=celestial__pb2.Empty.SerializeToString,
            ),
            'ModifyMachine': grpc.unary_unary_rpc_method_handler(
                    servicer.ModifyMachine,
                    request_deserializer=celestial__pb2.ModifyMachineRequest.FromString,
                    response_serializer=celestial__pb2.Empty.SerializeToString,
            ),
            'ModifyLinks': grpc.unary_unary_rpc_method_handler(
                    servicer.ModifyLinks,
                    request_deserializer=celestial__pb2.ModifyLinksRequest.FromString,
                    response_serializer=celestial__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'openfogstack.celestial.celestial.Celestial', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Celestial(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetHostInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/openfogstack.celestial.celestial.Celestial/GetHostInfo',
            celestial__pb2.Empty.SerializeToString,
            celestial__pb2.HostInfo.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def HostReady(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/openfogstack.celestial.celestial.Celestial/HostReady',
            celestial__pb2.Empty.SerializeToString,
            celestial__pb2.ReadyInfo.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Init(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/openfogstack.celestial.celestial.Celestial/Init',
            celestial__pb2.InitRequest.SerializeToString,
            celestial__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def InitRemotes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/openfogstack.celestial.celestial.Celestial/InitRemotes',
            celestial__pb2.InitRemotesRequest.SerializeToString,
            celestial__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StartPeering(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/openfogstack.celestial.celestial.Celestial/StartPeering',
            celestial__pb2.Empty.SerializeToString,
            celestial__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateMachine(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/openfogstack.celestial.celestial.Celestial/CreateMachine',
            celestial__pb2.CreateMachineRequest.SerializeToString,
            celestial__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ModifyMachine(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/openfogstack.celestial.celestial.Celestial/ModifyMachine',
            celestial__pb2.ModifyMachineRequest.SerializeToString,
            celestial__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ModifyLinks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/openfogstack.celestial.celestial.Celestial/ModifyLinks',
            celestial__pb2.ModifyLinksRequest.SerializeToString,
            celestial__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
