# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import peering_pb2 as peering__pb2


class PeeringStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartPeer = channel.unary_unary(
                '/openfogstack.celestial.peering.Peering/StartPeer',
                request_serializer=peering__pb2.StartPeerRequest.SerializeToString,
                response_deserializer=peering__pb2.Empty.FromString,
                )
        self.Route = channel.unary_unary(
                '/openfogstack.celestial.peering.Peering/Route',
                request_serializer=peering__pb2.RouteRequest.SerializeToString,
                response_deserializer=peering__pb2.Empty.FromString,
                )


class PeeringServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StartPeer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Route(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PeeringServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartPeer': grpc.unary_unary_rpc_method_handler(
                    servicer.StartPeer,
                    request_deserializer=peering__pb2.StartPeerRequest.FromString,
                    response_serializer=peering__pb2.Empty.SerializeToString,
            ),
            'Route': grpc.unary_unary_rpc_method_handler(
                    servicer.Route,
                    request_deserializer=peering__pb2.RouteRequest.FromString,
                    response_serializer=peering__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'openfogstack.celestial.peering.Peering', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Peering(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StartPeer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/openfogstack.celestial.peering.Peering/StartPeer',
            peering__pb2.StartPeerRequest.SerializeToString,
            peering__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Route(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/openfogstack.celestial.peering.Peering/Route',
            peering__pb2.RouteRequest.SerializeToString,
            peering__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
