"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file

This file is part of Celestial (https://github.com/OpenFogStack/celestial).
Copyright (c) 2021 Tobias Pfandzelter, The OpenFogStack Team.

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, version 3.

This program is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program. If not, see <http://www.gnu.org/licenses/>.
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class Empty(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___Empty = Empty

@typing_extensions.final
class Machine(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SHELL_FIELD_NUMBER: builtins.int
    ID_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    shell: builtins.int
    """allow -1 for ground stations"""
    id: builtins.int
    name: builtins.str
    """name is only used for ground stations"""
    def __init__(
        self,
        *,
        shell: builtins.int = ...,
        id: builtins.int = ...,
        name: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["id", b"id", "name", b"name", "shell", b"shell"]) -> None: ...

global___Machine = Machine

@typing_extensions.final
class StartPeerRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PUBLICKEY_FIELD_NUMBER: builtins.int
    INDEX_FIELD_NUMBER: builtins.int
    publickey: builtins.str
    index: builtins.int
    def __init__(
        self,
        *,
        publickey: builtins.str = ...,
        index: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["index", b"index", "publickey", b"publickey"]) -> None: ...

global___StartPeerRequest = StartPeerRequest

@typing_extensions.final
class RouteRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MACHINE_FIELD_NUMBER: builtins.int
    INDEX_FIELD_NUMBER: builtins.int
    BANDWIDTH_FIELD_NUMBER: builtins.int
    @property
    def machine(self) -> global___Machine: ...
    index: builtins.int
    bandwidth: builtins.int
    def __init__(
        self,
        *,
        machine: global___Machine | None = ...,
        index: builtins.int = ...,
        bandwidth: builtins.int = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["machine", b"machine"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["bandwidth", b"bandwidth", "index", b"index", "machine", b"machine"]) -> None: ...

global___RouteRequest = RouteRequest
