"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor = ...

class Empty(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...

    def __init__(self,
        ) -> None: ...
global___Empty = Empty

class Machine(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    SHELL_FIELD_NUMBER: builtins.int
    ID_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    shell: builtins.int = ...
    id: builtins.int = ...
    name: typing.Text = ...

    def __init__(self,
        *,
        shell : builtins.int = ...,
        id : builtins.int = ...,
        name : typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"id",b"id",u"name",b"name",u"shell",b"shell"]) -> None: ...
global___Machine = Machine

class StartPeerRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    PUBLICKEY_FIELD_NUMBER: builtins.int
    INDEX_FIELD_NUMBER: builtins.int
    publickey: typing.Text = ...
    index: builtins.int = ...

    def __init__(self,
        *,
        publickey : typing.Text = ...,
        index : builtins.int = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"index",b"index",u"publickey",b"publickey"]) -> None: ...
global___StartPeerRequest = StartPeerRequest

class RouteRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    MACHINE_FIELD_NUMBER: builtins.int
    INDEX_FIELD_NUMBER: builtins.int
    BANDWIDTH_FIELD_NUMBER: builtins.int
    index: builtins.int = ...
    bandwidth: builtins.int = ...

    @property
    def machine(self) -> global___Machine: ...

    def __init__(self,
        *,
        machine : typing.Optional[global___Machine] = ...,
        index : builtins.int = ...,
        bandwidth : builtins.int = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"machine",b"machine"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"bandwidth",b"bandwidth",u"index",b"index",u"machine",b"machine"]) -> None: ...
global___RouteRequest = RouteRequest
