# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: peering.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='peering.proto',
  package='openfogstack.celestial.peering',
  syntax='proto3',
  serialized_options=b'Z\t.;peering',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rpeering.proto\x12\x1eopenfogstack.celestial.peering\"\x07\n\x05\x45mpty\"2\n\x07Machine\x12\r\n\x05shell\x18\x01 \x01(\x03\x12\n\n\x02id\x18\x02 \x01(\x04\x12\x0c\n\x04name\x18\x03 \x01(\t\"4\n\x10StartPeerRequest\x12\x11\n\tpublickey\x18\x01 \x01(\t\x12\r\n\x05index\x18\x02 \x01(\x04\"j\n\x0cRouteRequest\x12\x38\n\x07machine\x18\x01 \x01(\x0b\x32\'.openfogstack.celestial.peering.Machine\x12\r\n\x05index\x18\x02 \x01(\x04\x12\x11\n\tbandwidth\x18\x03 \x01(\x04\x32\xcd\x01\n\x07Peering\x12\x64\n\tStartPeer\x12\x30.openfogstack.celestial.peering.StartPeerRequest\x1a%.openfogstack.celestial.peering.Empty\x12\\\n\x05Route\x12,.openfogstack.celestial.peering.RouteRequest\x1a%.openfogstack.celestial.peering.EmptyB\x0bZ\t.;peeringb\x06proto3'
)




_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='openfogstack.celestial.peering.Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=49,
  serialized_end=56,
)


_MACHINE = _descriptor.Descriptor(
  name='Machine',
  full_name='openfogstack.celestial.peering.Machine',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='shell', full_name='openfogstack.celestial.peering.Machine.shell', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='id', full_name='openfogstack.celestial.peering.Machine.id', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='openfogstack.celestial.peering.Machine.name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=58,
  serialized_end=108,
)


_STARTPEERREQUEST = _descriptor.Descriptor(
  name='StartPeerRequest',
  full_name='openfogstack.celestial.peering.StartPeerRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='publickey', full_name='openfogstack.celestial.peering.StartPeerRequest.publickey', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='index', full_name='openfogstack.celestial.peering.StartPeerRequest.index', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=110,
  serialized_end=162,
)


_ROUTEREQUEST = _descriptor.Descriptor(
  name='RouteRequest',
  full_name='openfogstack.celestial.peering.RouteRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='machine', full_name='openfogstack.celestial.peering.RouteRequest.machine', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='index', full_name='openfogstack.celestial.peering.RouteRequest.index', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='bandwidth', full_name='openfogstack.celestial.peering.RouteRequest.bandwidth', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=164,
  serialized_end=270,
)

_ROUTEREQUEST.fields_by_name['machine'].message_type = _MACHINE
DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['Machine'] = _MACHINE
DESCRIPTOR.message_types_by_name['StartPeerRequest'] = _STARTPEERREQUEST
DESCRIPTOR.message_types_by_name['RouteRequest'] = _ROUTEREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'peering_pb2'
  # @@protoc_insertion_point(class_scope:openfogstack.celestial.peering.Empty)
  })
_sym_db.RegisterMessage(Empty)

Machine = _reflection.GeneratedProtocolMessageType('Machine', (_message.Message,), {
  'DESCRIPTOR' : _MACHINE,
  '__module__' : 'peering_pb2'
  # @@protoc_insertion_point(class_scope:openfogstack.celestial.peering.Machine)
  })
_sym_db.RegisterMessage(Machine)

StartPeerRequest = _reflection.GeneratedProtocolMessageType('StartPeerRequest', (_message.Message,), {
  'DESCRIPTOR' : _STARTPEERREQUEST,
  '__module__' : 'peering_pb2'
  # @@protoc_insertion_point(class_scope:openfogstack.celestial.peering.StartPeerRequest)
  })
_sym_db.RegisterMessage(StartPeerRequest)

RouteRequest = _reflection.GeneratedProtocolMessageType('RouteRequest', (_message.Message,), {
  'DESCRIPTOR' : _ROUTEREQUEST,
  '__module__' : 'peering_pb2'
  # @@protoc_insertion_point(class_scope:openfogstack.celestial.peering.RouteRequest)
  })
_sym_db.RegisterMessage(RouteRequest)


DESCRIPTOR._options = None

_PEERING = _descriptor.ServiceDescriptor(
  name='Peering',
  full_name='openfogstack.celestial.peering.Peering',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=273,
  serialized_end=478,
  methods=[
  _descriptor.MethodDescriptor(
    name='StartPeer',
    full_name='openfogstack.celestial.peering.Peering.StartPeer',
    index=0,
    containing_service=None,
    input_type=_STARTPEERREQUEST,
    output_type=_EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Route',
    full_name='openfogstack.celestial.peering.Peering.Route',
    index=1,
    containing_service=None,
    input_type=_ROUTEREQUEST,
    output_type=_EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_PEERING)

DESCRIPTOR.services_by_name['Peering'] = _PEERING

# @@protoc_insertion_point(module_scope)
