"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file

This file is part of Celestial (https://github.com/OpenFogStack/celestial).
Copyright (c) 2021 Tobias Pfandzelter, The OpenFogStack Team.

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, version 3.

This program is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program. If not, see <http://www.gnu.org/licenses/>.
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import google.protobuf.timestamp_pb2
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class Empty(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___Empty = Empty

@typing_extensions.final
class ConstellationInfo(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MODEL_FIELD_NUMBER: builtins.int
    SHELLS_FIELD_NUMBER: builtins.int
    GROUNDSTATIONS_FIELD_NUMBER: builtins.int
    model: builtins.str
    shells: builtins.int
    @property
    def groundstations(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___GroundStationId]: ...
    def __init__(
        self,
        *,
        model: builtins.str = ...,
        shells: builtins.int = ...,
        groundstations: collections.abc.Iterable[global___GroundStationId] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["groundstations", b"groundstations", "model", b"model", "shells", b"shells"]) -> None: ...

global___ConstellationInfo = ConstellationInfo

@typing_extensions.final
class ShellRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SHELL_FIELD_NUMBER: builtins.int
    shell: builtins.int
    def __init__(
        self,
        *,
        shell: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["shell", b"shell"]) -> None: ...

global___ShellRequest = ShellRequest

@typing_extensions.final
class SGP4Options(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    STARTTIME_FIELD_NUMBER: builtins.int
    MODEL_FIELD_NUMBER: builtins.int
    MODE_FIELD_NUMBER: builtins.int
    BSTAR_FIELD_NUMBER: builtins.int
    NDOT_FIELD_NUMBER: builtins.int
    ARGPO_FIELD_NUMBER: builtins.int
    @property
    def starttime(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    model: builtins.str
    mode: builtins.str
    bstar: builtins.float
    ndot: builtins.float
    argpo: builtins.float
    def __init__(
        self,
        *,
        starttime: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        model: builtins.str = ...,
        mode: builtins.str = ...,
        bstar: builtins.float = ...,
        ndot: builtins.float = ...,
        argpo: builtins.float = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["starttime", b"starttime"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["argpo", b"argpo", "bstar", b"bstar", "mode", b"mode", "model", b"model", "ndot", b"ndot", "starttime", b"starttime"]) -> None: ...

global___SGP4Options = SGP4Options

@typing_extensions.final
class NetworkConfig(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    BANDWIDTH_FIELD_NUMBER: builtins.int
    ISLPROPAGATION_FIELD_NUMBER: builtins.int
    MINCOMMSALTITUDE_FIELD_NUMBER: builtins.int
    MINELEVATION_FIELD_NUMBER: builtins.int
    GSTPROPAGATION_FIELD_NUMBER: builtins.int
    GROUNDSTATIONCONNECTIONTYPE_FIELD_NUMBER: builtins.int
    bandwidth: builtins.int
    islpropagation: builtins.float
    mincommsaltitude: builtins.int
    minelevation: builtins.float
    gstpropagation: builtins.float
    groundstationconnectiontype: builtins.str
    def __init__(
        self,
        *,
        bandwidth: builtins.int = ...,
        islpropagation: builtins.float = ...,
        mincommsaltitude: builtins.int = ...,
        minelevation: builtins.float = ...,
        gstpropagation: builtins.float = ...,
        groundstationconnectiontype: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["bandwidth", b"bandwidth", "groundstationconnectiontype", b"groundstationconnectiontype", "gstpropagation", b"gstpropagation", "islpropagation", b"islpropagation", "mincommsaltitude", b"mincommsaltitude", "minelevation", b"minelevation"]) -> None: ...

global___NetworkConfig = NetworkConfig

@typing_extensions.final
class ComputeConfig(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VCPU_FIELD_NUMBER: builtins.int
    MEM_FIELD_NUMBER: builtins.int
    HT_FIELD_NUMBER: builtins.int
    DISK_FIELD_NUMBER: builtins.int
    KERNEL_FIELD_NUMBER: builtins.int
    ROOTFS_FIELD_NUMBER: builtins.int
    vcpu: builtins.int
    mem: builtins.int
    ht: builtins.bool
    disk: builtins.int
    kernel: builtins.str
    rootfs: builtins.str
    def __init__(
        self,
        *,
        vcpu: builtins.int = ...,
        mem: builtins.int = ...,
        ht: builtins.bool = ...,
        disk: builtins.int = ...,
        kernel: builtins.str = ...,
        rootfs: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["disk", b"disk", "ht", b"ht", "kernel", b"kernel", "mem", b"mem", "rootfs", b"rootfs", "vcpu", b"vcpu"]) -> None: ...

global___ComputeConfig = ComputeConfig

@typing_extensions.final
class ShellInfo(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PLANES_FIELD_NUMBER: builtins.int
    SATS_FIELD_NUMBER: builtins.int
    ALTITUDE_FIELD_NUMBER: builtins.int
    INCLINATION_FIELD_NUMBER: builtins.int
    ARCOFASCENDINGSNODES_FIELD_NUMBER: builtins.int
    ECCENTRICITY_FIELD_NUMBER: builtins.int
    ACTIVESATS_FIELD_NUMBER: builtins.int
    NETWORK_FIELD_NUMBER: builtins.int
    COMPUTE_FIELD_NUMBER: builtins.int
    SGP4_FIELD_NUMBER: builtins.int
    planes: builtins.int
    sats: builtins.int
    altitude: builtins.float
    inclination: builtins.float
    arcofascendingsnodes: builtins.float
    eccentricity: builtins.float
    @property
    def activeSats(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___SatelliteId]: ...
    @property
    def network(self) -> global___NetworkConfig: ...
    @property
    def compute(self) -> global___ComputeConfig: ...
    @property
    def sgp4(self) -> global___SGP4Options: ...
    def __init__(
        self,
        *,
        planes: builtins.int = ...,
        sats: builtins.int = ...,
        altitude: builtins.float = ...,
        inclination: builtins.float = ...,
        arcofascendingsnodes: builtins.float = ...,
        eccentricity: builtins.float = ...,
        activeSats: collections.abc.Iterable[global___SatelliteId] | None = ...,
        network: global___NetworkConfig | None = ...,
        compute: global___ComputeConfig | None = ...,
        sgp4: global___SGP4Options | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["_sgp4", b"_sgp4", "compute", b"compute", "network", b"network", "sgp4", b"sgp4"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["_sgp4", b"_sgp4", "activeSats", b"activeSats", "altitude", b"altitude", "arcofascendingsnodes", b"arcofascendingsnodes", "compute", b"compute", "eccentricity", b"eccentricity", "inclination", b"inclination", "network", b"network", "planes", b"planes", "sats", b"sats", "sgp4", b"sgp4"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_sgp4", b"_sgp4"]) -> typing_extensions.Literal["sgp4"] | None: ...

global___ShellInfo = ShellInfo

@typing_extensions.final
class SatelliteId(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SHELL_FIELD_NUMBER: builtins.int
    SAT_FIELD_NUMBER: builtins.int
    shell: builtins.int
    sat: builtins.int
    def __init__(
        self,
        *,
        shell: builtins.int = ...,
        sat: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["sat", b"sat", "shell", b"shell"]) -> None: ...

global___SatelliteId = SatelliteId

@typing_extensions.final
class Pos(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    X_FIELD_NUMBER: builtins.int
    Y_FIELD_NUMBER: builtins.int
    Z_FIELD_NUMBER: builtins.int
    x: builtins.float
    y: builtins.float
    z: builtins.float
    def __init__(
        self,
        *,
        x: builtins.float = ...,
        y: builtins.float = ...,
        z: builtins.float = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["x", b"x", "y", b"y", "z", b"z"]) -> None: ...

global___Pos = Pos

@typing_extensions.final
class SatelliteInfo(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    POSITION_FIELD_NUMBER: builtins.int
    ACTIVE_FIELD_NUMBER: builtins.int
    CONNECTEDSATS_FIELD_NUMBER: builtins.int
    CONNECTEDGST_FIELD_NUMBER: builtins.int
    @property
    def position(self) -> global___Pos: ...
    active: builtins.bool
    @property
    def connectedSats(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___ConnectedSatInfo]: ...
    @property
    def connectedGST(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___GroundStationId]: ...
    def __init__(
        self,
        *,
        position: global___Pos | None = ...,
        active: builtins.bool = ...,
        connectedSats: collections.abc.Iterable[global___ConnectedSatInfo] | None = ...,
        connectedGST: collections.abc.Iterable[global___GroundStationId] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["position", b"position"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["active", b"active", "connectedGST", b"connectedGST", "connectedSats", b"connectedSats", "position", b"position"]) -> None: ...

global___SatelliteInfo = SatelliteInfo

@typing_extensions.final
class ConnectedSatInfo(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SAT_FIELD_NUMBER: builtins.int
    DISTANCE_FIELD_NUMBER: builtins.int
    DELAY_FIELD_NUMBER: builtins.int
    BANDWIDTH_FIELD_NUMBER: builtins.int
    @property
    def sat(self) -> global___SatelliteId: ...
    distance: builtins.float
    delay: builtins.float
    bandwidth: builtins.float
    def __init__(
        self,
        *,
        sat: global___SatelliteId | None = ...,
        distance: builtins.float = ...,
        delay: builtins.float = ...,
        bandwidth: builtins.float = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["sat", b"sat"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["bandwidth", b"bandwidth", "delay", b"delay", "distance", b"distance", "sat", b"sat"]) -> None: ...

global___ConnectedSatInfo = ConnectedSatInfo

@typing_extensions.final
class ConnectedGSTInfo(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    GST_FIELD_NUMBER: builtins.int
    DISTANCE_FIELD_NUMBER: builtins.int
    DELAY_FIELD_NUMBER: builtins.int
    BANDWIDTH_FIELD_NUMBER: builtins.int
    @property
    def gst(self) -> global___GroundStationId: ...
    distance: builtins.float
    delay: builtins.float
    bandwidth: builtins.float
    def __init__(
        self,
        *,
        gst: global___GroundStationId | None = ...,
        distance: builtins.float = ...,
        delay: builtins.float = ...,
        bandwidth: builtins.float = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["gst", b"gst"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["bandwidth", b"bandwidth", "delay", b"delay", "distance", b"distance", "gst", b"gst"]) -> None: ...

global___ConnectedGSTInfo = ConnectedGSTInfo

@typing_extensions.final
class GroundStationId(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    name: builtins.str
    def __init__(
        self,
        *,
        name: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["name", b"name"]) -> None: ...

global___GroundStationId = GroundStationId

@typing_extensions.final
class GroundStationInfo(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    POSITION_FIELD_NUMBER: builtins.int
    LATITUDE_FIELD_NUMBER: builtins.int
    LONGITUDE_FIELD_NUMBER: builtins.int
    NETWORK_FIELD_NUMBER: builtins.int
    COMPUTE_FIELD_NUMBER: builtins.int
    CONNECTEDSATS_FIELD_NUMBER: builtins.int
    @property
    def position(self) -> global___Pos: ...
    latitude: builtins.float
    longitude: builtins.float
    @property
    def network(self) -> global___NetworkConfig: ...
    @property
    def compute(self) -> global___ComputeConfig: ...
    @property
    def connectedSats(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___ConnectedSatInfo]: ...
    def __init__(
        self,
        *,
        position: global___Pos | None = ...,
        latitude: builtins.float = ...,
        longitude: builtins.float = ...,
        network: global___NetworkConfig | None = ...,
        compute: global___ComputeConfig | None = ...,
        connectedSats: collections.abc.Iterable[global___ConnectedSatInfo] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["compute", b"compute", "network", b"network", "position", b"position"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["compute", b"compute", "connectedSats", b"connectedSats", "latitude", b"latitude", "longitude", b"longitude", "network", b"network", "position", b"position"]) -> None: ...

global___GroundStationInfo = GroundStationInfo

@typing_extensions.final
class Segment(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SOURCESHELL_FIELD_NUMBER: builtins.int
    SOURCESAT_FIELD_NUMBER: builtins.int
    TARGETSHELL_FIELD_NUMBER: builtins.int
    TARGETSAT_FIELD_NUMBER: builtins.int
    DELAY_FIELD_NUMBER: builtins.int
    DISTANCE_FIELD_NUMBER: builtins.int
    BANDWIDTH_FIELD_NUMBER: builtins.int
    sourceShell: builtins.int
    sourceSat: builtins.int
    targetShell: builtins.int
    targetSat: builtins.int
    delay: builtins.float
    distance: builtins.float
    bandwidth: builtins.float
    def __init__(
        self,
        *,
        sourceShell: builtins.int = ...,
        sourceSat: builtins.int = ...,
        targetShell: builtins.int = ...,
        targetSat: builtins.int = ...,
        delay: builtins.float = ...,
        distance: builtins.float = ...,
        bandwidth: builtins.float = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["bandwidth", b"bandwidth", "delay", b"delay", "distance", b"distance", "sourceSat", b"sourceSat", "sourceShell", b"sourceShell", "targetSat", b"targetSat", "targetShell", b"targetShell"]) -> None: ...

global___Segment = Segment

@typing_extensions.final
class PathRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SOURCESHELL_FIELD_NUMBER: builtins.int
    SOURCESAT_FIELD_NUMBER: builtins.int
    TARGETSHELL_FIELD_NUMBER: builtins.int
    TARGETSAT_FIELD_NUMBER: builtins.int
    sourceShell: builtins.int
    sourceSat: builtins.int
    targetShell: builtins.int
    targetSat: builtins.int
    def __init__(
        self,
        *,
        sourceShell: builtins.int = ...,
        sourceSat: builtins.int = ...,
        targetShell: builtins.int = ...,
        targetSat: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["sourceSat", b"sourceSat", "sourceShell", b"sourceShell", "targetSat", b"targetSat", "targetShell", b"targetShell"]) -> None: ...

global___PathRequest = PathRequest

@typing_extensions.final
class PathInfo(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PATHS_FIELD_NUMBER: builtins.int
    @property
    def paths(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Path]: ...
    def __init__(
        self,
        *,
        paths: collections.abc.Iterable[global___Path] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["paths", b"paths"]) -> None: ...

global___PathInfo = PathInfo

@typing_extensions.final
class Path(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    DISTANCE_FIELD_NUMBER: builtins.int
    DELAY_FIELD_NUMBER: builtins.int
    BANDWIDTH_FIELD_NUMBER: builtins.int
    SEGMENTS_FIELD_NUMBER: builtins.int
    distance: builtins.float
    delay: builtins.float
    bandwidth: builtins.float
    @property
    def segments(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Segment]: ...
    def __init__(
        self,
        *,
        distance: builtins.float = ...,
        delay: builtins.float = ...,
        bandwidth: builtins.float = ...,
        segments: collections.abc.Iterable[global___Segment] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["bandwidth", b"bandwidth", "delay", b"delay", "distance", b"distance", "segments", b"segments"]) -> None: ...

global___Path = Path
