#
# This file is part of Celestial (https://github.com/OpenFogStack/celestial).
# Copyright (c) 2024 Tobias Pfandzelter, The OpenFogStack Team.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, version 3.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#

bbox = [-90.0, -180.0, 90.0, 180.0]
resolution = 1
duration = 86400

[network_params]
bandwidth_kbits = 10_000_000
min_elevation = 40
ground_station_connection_type = "all"

[compute_params]
vcpu_count = 1
mem_size_mib = 512
disk_size_mib = 10
kernel = "x.bin"
rootfs = "x.img"

[[shell]]
planes = 34
sats = 34
altitude_km = 630
inclination = 51.9
arc_of_ascending_nodes = 360.0
eccentricity = 0.0

[[shell]]
planes = 36
sats = 36
altitude_km = 610
inclination = 42.0
arc_of_ascending_nodes = 360.0
eccentricity = 0.0

[[shell]]
planes = 28
sats = 28
altitude_km = 590
inclination = 33.0
arc_of_ascending_nodes = 360.0
eccentricity = 0.0

[[ground_station]]
name = "TUBerlin"
lat = 52.51499
long = 13.32674
