#!/bin/sh
#
# This file is part of Celestial (https://github.com/OpenFogStack/celestial).
# Copyright (c) 2024 Tobias Pfandzelter, The OpenFogStack Team.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, version 3.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#

# clock synchronization
chronyc makestep
sleep 1
chronyc makestep
# chronyc tracking

# network setup
IP=$(/sbin/ip route | awk '/default/ { print $3 }')
echo "$IP   info.celestial" >> /etc/hosts

echo "Celestial: Starting user script..."

/bin/sh app.sh

echo "Celestial: User script finished, shutting down..."
reboot # reboot actually shuts down the microVM in Firecracker
